### ISSUE TITLE
Isochrone issues

### ISSUE THREAD

**Issue by andycasey** [AnnieJumpCannon/RAVE#29]
@keithhawkins:
- [x] Still no NGC 1851 isochrone in the repository
- [ ] All isochrones are `mis-ordered' in the sense that matplotlib produces and additional line when going down to the clump -- re-order the isochrone so that artefact no longer exists
- [x] All isochrones show a hook at the lowest loggs -- these need removing

I will re-write the plotting code so that:
- [x] The top panels and the lower panels have the **same color map**
- [x] Errors on values
- [x] Isochrones go underneath the data
- [x] `2xN` panels not `Nx2`
- [x] Make tickmarks and limits the same way as other figures
- [x] Fix white space and axes so that they are actually square.

**Comment by andycasey** [comment]
Open cluster figures updated in a01b86c

**Comment by keithhawkins** [comment]
On it when I get in. Ngc 1851 isochrone is on my laptop must have forgotton
to git add it I will do that.

I haven't found a Pleiades isochrone that works partly I think because to
me it appears the slope of the stars may be slightly off (I.e. a hint of a
turnoff at approx. 6200K when there shouldn't be one well before 7000K)

On Sep 8, 2016 5:51 AM, "Andy Casey" notifications@github.com wrote:

@keithhawkins https://github.com/keithhawkins:
- Still no NGC 1851 isochrone
- All isochrones are `mis-ordered' in the sense that matplotlib produces
  and additional line when going down to the clump -- re-order the isochrone
  so that artefact no longer exists
- All isochrones show a hook at the lowest loggs -- these need removing

I will re-write the plotting code so that:
- The top panels and the lower panels have the _same color map_
- Errors on values
- Isochrones go underneath the data
- 2xN panels not Nx2
- Make tickmarks and limits the same way as other figures
- Fix white space and axes so that they are actually square.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/AnnieJumpCannon/RAVE/issues/29, or mute the thread

**Comment by mkness** [comment]
which isochrones are you using (Can't find the ref in the text). 0.15 Gyr Padova isochrone still looks bad for the Pleiades?

**Comment by keithhawkins** [comment]
Padova/PARSEC isochrones are used ( i used the Bressan2012 reference for that). The Pleiades doesn’t look as nice. I have double checked that the right isochrone was being used. To me it appears that there is a a hint of a turnoff at ~6200K in the Pleiades stars in the diagram which is way cooler than Id expect for such a young cluster. I have looked into some empirically calibrated Pleiades clusters. most just have the photometry. I did find one that has the Teff-logg but the isochrone looks even worse.

**Comment by andycasey** [comment]
Ness which isochrone did you use in your 15 paper? Is that sitting on a hard drive somewhere ?

**Comment by mkness** [comment]
Yes I used the Padova ones that Keith is already using. can dig it up and send it along though just in case it is different. will do

**Comment by andycasey** [comment]
Nah if it's the same one then don't worry -- I am sure it could be fixed with a harsher selection of members, so we will discuss that instead of blaming isochrones.
